(string<=? "a" "bbb")
(eqv? "a" "b")
(eqv? 1 3)
(eqv? 1 3)
(cons '(this is) '())
(eqv? 'atom 'atom)
(car '(a b c))
(car '(a))
(car '(m b . c))
(car 'a)
(car 'a 'b)
(cdr '(a b c))
(cdr '(a b))
(cdr '(a))
(cdr '(a . b))
(cdr '(m b . c))
(cdr 'm)
(cdr 'a 'b)
(cond ((> 3 2) 'greater) ((< 3 2) 'less))
(cond ((> 3 3) 'greater) ((<= 3 3) 'less) (else 'equal))
(case (* 2 3) ((2 3 5 7) 'prime) ((1 4 6 8) 'composite))
(case (car '(c d)) ((a e i o u) 'vowel) ((w y) 'semivowel) (else 'consonant))
